# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7af74b0cca352752001026f35bad28fae8062c1b746f0a0e858a9a2f92358eae49527fd28ac10bece2e43cc384e5d473b5f3b1ed7bd4050a897bb19f44dc7fbc

test:
  secret_key_base: 1ff1b5f18592355aa78be9ca4379b8fac2a8cdd71476de1b66a7768b569ccadb1f1b5c963b33a92d1fbe0410b2198cc8ef05b53defda1a4a27a5e69b4f693cd1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
